### ISSUE TITLE
Display of inscriptions in a collection or single publication-Bib only

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/usepweb_project#17]
Bib only inscriptions should display the bibliography in the box and have no link to anything else.

**Comment by emylonas** [comment]
This should be handled as the search results are compiled. Not sure of best way to do it yet.

**Comment by crotger** [comment]
covered by #26

**Comment by emylonas** [comment]
Try opening this page: http://worfdev.services.brown.edu/projects/usep/collections/NY.NY.MMA/

it hangs, probably because there are tons of inscriptions and they all have only bibliography

**Comment by emylonas** [comment]
same as #56, closing
