### ISSUE TITLE
fixes on Zak's new design - view of single collection

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/usepweb_project#26]
See display on worfdev. 

1. if there is no image, then we should not have a "no image" thumbnail. It should just have the text. In some cases, the file itself points to a "noimage.jpg" in that case, don't do anything, we have to eliminate them from the files. But if it's being substittuted by the code, then don't show anything

2. Files that have transcription should not say (transcription). 

3. Files that have only a bibligraphy, ideally should print the bib info directly in the box. 

4. Metadata inscriptions can say "metadata only". Mostly as they do now.

**Comment by emylonas** [comment]
btw, this should probably also work on publication view and search results

**Comment by emylonas** [comment]
Metadata only -> No Transcription

**Comment by crotger** [comment]
finished item 1 and 2 so far

**Comment by emylonas** [comment]
Clarification - what do you use to tell if there is not image? 

- checking for noimage.jpg 
- checking for whatever other noimage tag exists
- just ignoring it if there is nothing in the `graphic url="">`  attribute

**Comment by crotger** [comment]
a blank graphic url will now show nothing. graphic urls set to noimage.jpg will still show that.

**Comment by crotger** [comment]
PR open at #28 !
addresses the above at least on collection pages

**Comment by emylonas** [comment]
Not working cleanly, not sure why- see 
http://worfdev.services.brown.edu/projects/usep/publication/GRBS/
The citation isn't showing up. There are some others as well. 
it may be because of the abbreviation.

Also, the citation doesn't show  up when looking at a group of inscriptions that all are mentioned in the same publication.
