### ISSUE TITLE
Add licensing info to footer of all pages

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/usepweb_project#71]
All pages should display a CC license in the footer as follows: https://creativecommons.org/licenses/by-nc-sa/4.0/
It should appear like this: https://ircyr2020.inslib.kcl.ac.uk/en/

When we get a landing page, we can display the license in a more central location

**Comment by atbradley** [comment]
@emylonas You can see my recent commit live at https://dlibwwwcit.services.brown.edu/projects/usep/publications/. I wasn't sure how long to tinker with the CSS.

**Comment by atbradley** [comment]
And it breaks on the collections page: https://dlibwwwcit.services.brown.edu/projects/usep/collections/MA.Camb.HU.Sack/ I'll look some more this afternoon.

**Comment by atbradley** [comment]
@birkin @emylonas fixed my previous issue by removing `position: absolute;` from the CSS for the `#container` that holds the list of inscriptions. It looks better to me, but I don't know why it was absolutely positioned in the first place, which makes me nervous about changing it in production.

**Comment by birkin** [comment]
@atbradley @emylonas re _"...but I don't know why it was absolutely positioned in the first place, which makes me nervous about changing it in production..."_ No idea, this project has evolved with lots of input from predecessors to me, me, and students. Suggestion: if your and Elli's fix looks good on the main pages you check, go ahead and...
- if dev is out-of-sync with master/main, which I believe it is from another pull-request
    - merge dev into main
    - tag a release
    - deploy main to production-server via script
- merge your branch with this fix into dev
- deploy to dev-server via script
- confirm w/Elli that all still looks reasonable
- merge dev into main
- tag a release
- deploy main to production-server via script

**Comment by emylonas** [comment]
@atbradley This looks very nice. 

1. There some pages where it doesn't align at the bottom of the page: 
https://dlibwwwcit.services.brown.edu/projects/usep/publication/Williams/
also the search page but that page is a mess in general
 
2. when you go to any page that loads XML through the XSLT process, the "LOADING..." message is on top of the copyright info. That may be some bit of the positioning.
https://dlibwwwcit.services.brown.edu/projects/usep/inscription/IL.Urb.UI.SM.G.1930.01.0001/

Fixing the second would make the page loads less confusing. The first would be nice but not crucial, but I think they are probably due to the same CSS.
